**Forbenius Norm ||X||f 

In [1]:
import numpy as np 

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
np.linalg.norm(x)

5.477225575051661

In [4]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [5]:
b = np.array([[1,9],[2,0]])
b

array([[1, 9],
       [2, 0]])

In [6]:
np.dot(A, b)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [7]:
x_sym = np.array([[0,1,2], [1,7,8], [2,8,9]])
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [8]:
x_sym.T == x_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
I = np.array([[1,0,0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
x_np = np.array([25,2,5])
x_np

array([25,  2,  5])

In [11]:
np.dot(I, x_np)

array([25,  2,  5])

**MAtrix Inversion

In [12]:
x = np.array([[4,2], [-5,-3]])
x

array([[ 4,  2],
       [-5, -3]])

In [13]:
y = np.array([4,-7])
y

array([ 4, -7])

In [14]:
x_inv = np.linalg.inv(x)
x_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [15]:
w = np.dot(x_inv, y)
w

array([-1.,  4.])