In [1]:
import numpy as np

In [2]:
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
x.shape

(3, 2)

In [4]:
x.size

6

In [5]:
x[:,0]

array([25,  5,  3])

In [6]:
x[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

In [7]:
A = x + 2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [8]:
A + x

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [9]:
A * x

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [10]:
np.dot(x, A.T)

array([[683, 231, 143],
       [239, 763, 259],
       [109, 217,  78]])

In [11]:
import tensorflow as tf


tf.reduce_sum(tf.multiply(x, A))

<tf.Tensor: shape=(), dtype=int32, numpy=1524>

In [12]:
w = np.array([-1, 2, -2])
y = np.array([5, 10, 0])
np.dot(w, y)

15

In [13]:
v = np.array([[25, 10], [-2, 1]])
p = np.array([[-1, 7], [10, 8]])

v*p

array([[-25,  70],
       [-20,   8]])