In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
type(x)

numpy.ndarray

In [5]:
type(x[0])

numpy.int32

In [6]:
x_t = x.T
x_t

array([25,  2,  5])

In [7]:
y = np.array([[25, 2, 5]])

In [8]:
y.shape

(1, 3)

In [9]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [10]:
y_t.shape

(3, 1)

Vectors in PyTorch and TensorFLow

In [11]:
import torch

In [12]:
import tensorflow as tf

In [13]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [14]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>